Changes to support meta annotations
krraghavan/mongodb-aggregate-query-support pull request #19
Opened 2017-09-11 04:14 UTC by AnushaKasa

-- Adding a new meta annotation - AggregateMetaAnnotation
-- Changing AggregateQueryProvider2 to support aggregate pipeline annotations in meta annotation

2017-09-12 16:22 UTC, krraghavan commented on src/main/java/com/cisco/mongodb/aggregate/support/annotation/AggregateMetaAnnotation.java
> +@JacksonAnnotation
Why do we need JacksonAnnotation?

2017-09-12 16:28 UTC, krraghavan requested changes
Just one comment.  Not sure why we need Jackson dependency.

2017-09-12 17:33 UTC, AnushaKasa commented on src/main/java/com/cisco/mongodb/aggregate/support/annotation/AggregateMetaAnnotation.java
> +@JacksonAnnotation
Removed the annotation

2017-09-13 04:59 UTC, krraghavan approved these changes

2017-09-13 04:59 UTC, merged